//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdultEmergencyContact
    {
        public int Id { get; set; }
        public string contactName { get; set; }
        public string relationship { get; set; }
        public string primaryNum { get; set; }
        public string alternateNum { get; set; }
        public string nameNearestRelative { get; set; }
        public string NRrelationship { get; set; }
        public string NRstreetAddress { get; set; }
        public string NRcity { get; set; }
        public string NRstate { get; set; }
        public string NRzip { get; set; }
        public string NRprimaryNum { get; set; }
        public string NRworkNum { get; set; }
        public string NRcellNum { get; set; }
    }
}
