//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolEmergencyContact
    {
        public int Id { get; set; }
        public string parentNameOne { get; set; }
        public string parentOneRelationship { get; set; }
        public string parentOneAddress { get; set; }
        public string parentOneCity { get; set; }
        public string parentOneState { get; set; }
        public string parentOneZip { get; set; }
        public string parentOnePrimaryNum { get; set; }
        public string parentOneWorkNum { get; set; }
        public string parentOneCellNum { get; set; }
        public string parentOneEmail { get; set; }
        public string residesWithP1 { get; set; }
        public string parentNameTwo { get; set; }
        public string parentTwoRelationship { get; set; }
        public string parentTwoAddress { get; set; }
        public string parentTwoCity { get; set; }
        public string parentTwoState { get; set; }
        public string parentTwoZip { get; set; }
        public string parentTwoPrimaryNum { get; set; }
        public string parentTwoWorkNum { get; set; }
        public string parentTwoCellNum { get; set; }
        public string parentTwoEmail { get; set; }
        public string residesWithP2 { get; set; }
        public string EContactName { get; set; }
        public string EContactRelationship { get; set; }
        public string EContactPrimaryNum { get; set; }
        public string EContactWorkNum { get; set; }
        public string EContactCellNum { get; set; }
    }
}
