//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolPolicy
    {
        public int id { get; set; }
        public string attendance { get; set; }
        public string tobacco { get; set; }
        public string internetAccess { get; set; }
        public string studentInsurance { get; set; }
        public string fieldTrips { get; set; }
        public string drugTesting { get; set; }
        public string noticeOfDisclosures { get; set; }
        public string cellPhoneContact { get; set; }
        public string releaseForPhotography { get; set; }
    }
}
