//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolHealthInfo
    {
        public int Id { get; set; }
        public string primaryPhysician { get; set; }
        public string otherPhysician { get; set; }
        public string pPhysicianPhoneNum { get; set; }
        public string oPhysicianPhoneNum { get; set; }
        public string diabeticType { get; set; }
        public string allergies { get; set; }
        public string heartIssues { get; set; }
        public string metabolic { get; set; }
        public string jointMuscle { get; set; }
        public string chronicIllness { get; set; }
        public string migraines { get; set; }
        public string neurological { get; set; }
        public string pulmonary { get; set; }
        public string asthma { get; set; }
        public string other { get; set; }
        public string otherMeds { get; set; }
        public string specificFirstAidNeeds { get; set; }
        public string repPermissionForTreatment { get; set; }
    }
}
