//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrollment_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighSchoolConfidentialInfo
    {
        public int Id { get; set; }
        public string foodStamps { get; set; }
        public string dependentChildrenAid { get; set; }
        public string supplementaryIncome { get; set; }
        public string housingAssistance { get; set; }
        public string none { get; set; }
        public string homeless { get; set; }
        public string agedOutFosterCare { get; set; }
        public string outOfWorkforce { get; set; }
    }
}
